
stages:
    - build

build:node10:
    image: node:10
    stage: build
    before_script:
        - npm ci
    script:
        - npm run build
    only:
        - master
    artifacts:
        name: "build-node10-{$CI_COMMIT_REF_SLUG}-{$CI_COMMIT_SHORT_SHA}"
        paths:
            - dist

build:node11:
    image: node:11
    stage: build
    before_script:
        - npm ci
    script:
        - npm run build
    only:
        - master
    artifacts:
        name: "build-node11-{$CI_COMMIT_REF_SLUG}-{$CI_COMMIT_SHORT_SHA}"
        paths:
            - dist

build:node12:
    image: node:12
    stage: build
    before_script:
        - npm ci
    script:
        - npm run build
    only:
        - master
    artifacts:
        name: "build-node12-{$CI_COMMIT_REF_SLUG}-{$CI_COMMIT_SHORT_SHA}"
        paths:
            - dist
