name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10, 11, 12, 13]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: NPM install and build
    - run: npm ci
    - run: npm run build --if-present
    - run: node -v > dist/node-version.txt
      env:
        CI: true
