name: CI Prod tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 */10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18, 20, 22]

    steps:
      - name: Getting configuration from GitHub
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run build
        run: |
          npm i -g tateru-cli
          tateru-cli config.json --env prod
          node -v > dist/node-version.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-node-${{ matrix.node-version }}
          path: dist
